### ISSUE TITLE
Falx does not show in wallet cannot add manually 

### ISSUE THREAD

**Issue by Sublimedegree357** [FalconX-DEX/Falx-Support#1]
**Describe the bug**

cannot add falx to wallet tried on phantom Solflare iPhone and iOS web.  This issue started a week ago. When I harvest falx it shows harvested but nothing goes/appears in wallet. 

Bought falx on a different wallet to transfer to my affect wallet C28CpZLQDtZnZSKNHu3HUAg34FHnG44crVez2Yt9NqsA
And cannot transfer falx to the affected wallet. I can transfer and add other tokens. 

On the falx DEX it shows a balance but swap does not work it fails most recent attempt June 6 2024, 8:43 est here is the hash 3FbeYGpM2gApW1qhXAuXwNWXZAsaCmVU5jXtGxBZhgHBWZboKjRMChYgkMrF8xmwVQ9xmvnYrLuuPfkhkvmeoKpR.

video too big to upload

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lissanro** [comment]
Could you please try again and report back if this is still an issue? Thanks.

**Comment by Jk0x0kJ** [comment]
Upon our triage, we observed that your last successful harvest occurred 4 days ago. Below are the hashes of the successful harvest requests:

```
5RPsSAypFnsDMfcgWw339bF9ZFBBjCjQmimKz6hXSBYxDT6iAPBevgjzab3LH7pMBbm6ETe3A1aCEZTTqMjRek7N
etnwUbpAiKgynU5Y8sVZKEdJDfPDFu9AuNWDYYxM5jML4dmNmmf6Zd5xncoAZXDcLMUarw5WPH6arjiLdfjg3pf
```

Regarding the issue you mentioned about not being able to receive tokens from transfers, our investigation indicates that this issue is not related to the token or our system. It appears to be directly related to your end.

Please verify your configurations and try again. If you need further assistance, feel free to provide additional details about your setup and any error messages you are encountering.

@Sublimedegree357

**Comment by Sublimedegree357** [comment]
Again falx token
Afo4NumBNHDXc7m7p6qjZ1pF3LbqYfG5k1CNrGve8rVu does not appear in my wallet
and cannot be added to my wallet Solflare or phantom.
Yes I harvested but the falx token does not show in my wallet, which was
also one of my concerns. I did mention this specifically.

See below when the flax address is paste in phantom. I tried on Solflare
also, falx did show me in my wallet now it does not and I cannot add it
mannully or from the token list to my wallet. Additionally, my wallet will
not accept falx transfers.

 In the response this was not addressed, only thing addressed was
successful harvest and falx not appearing in wallet was not addressed or
looked at.

**Comment by Jk0x0kJ** [comment]
As mentioned, we are unable to triage the issue of adding tokens to your wallet from our end. However, we will triage your unsuccessful harvest request based on your statement. If you encounter any error messages, please share them with us. In the meantime, please try adding the Falx token using a different wallet.

@Sublimedegree357

**Comment by Jk0x0kJ** [comment]
This might be related to issue #3. Please check it out with the latest update and let us know. @Sublimedegree357

**Comment by Sublimedegree357** [comment]
it did not work, error no valid pool:  i did try to unstake to see what
would happen. half my falx gone, i bought early now losing late. hash
https://explorer.solana.com/tx/3mH32GTEh5oYw9vu6SMdTnHFAd2SiDNxiXYReZTKPpUc9cEKJp8ZprBtT99Ef9r38gDWJkkpc1nnbENpWgns4KGf?cluster=mainnet-beta
nothing went to my wallet. C28CpZLQDtZnZSKNHu3HUAg34FHnG44crVez2Yt9NqsA
june 10 around 1030pm est.

please help me this is the only token that is doing this, and i know the
potential so it really hurts.

**Comment by Jk0x0kJ** [comment]
After a thorough review, we discovered that you interacted with the program (contract) identified by `AwQrxvuJqGNME6EDk66GcHQkKLjXPkbcRo3179ZDgEQA` in this transaction: [Solscan Transaction](https://solscan.io/tx/2TTU2ckGAkMwJAZeuaF1jyPwEghvvpTTJjYr5FB27EUuCXmBcecBDfMbk2cL8Q578zpAi6KxmvAJm1BTnFZatp7).

In this transaction, you signed and gave permission to transfer your FALX ATA to the address `D8hECG64Wn2eXNyLAQ2tqy1mPP9Fhhj5xd6iMDyv2DyR`. Consequently, you no longer own your **FALX ATA**; the new owner is `D8hECG64Wn2eXNyLAQ2tqy1mPP9Fhhj5xd6iMDyv2DyR`.

Due to this interaction with a malicious contract, you are unable to use your address for **FALX** transactions.

@Sublimedegree357

**Comment by Sublimedegree357** [comment]
Damn
