### ISSUE TITLE
AirDrop not received

### ISSUE THREAD

**Issue by cedricf50** [FalconX-DEX/Falx-Support#25]
Hi

I dont received airdrop.
However, I stacked 482683 Falx and I filled the form on time

my wallet address:
8VseLCqeDHoqD5w6VbotHm9gmVY5GECsojoo1e61MKqx

can you watch please?

Thank you

**Comment by Lissanro** [comment]
Please note that airdrop was not intended for users who staked FALX. Airdrop only was intended for users who staked SOLX in the past and did not unstake before April 28. Since many users forgot what they staked or if they held their staking long enough, we used accurate blockchain data, and according to it you did not have any SOLX staked by April 28 in this wallet.
