### ISSUE TITLE
SOLX AIRDROP

### ISSUE THREAD

**Issue by YourFlyness** [FalconX-DEX/Falx-Support#39]
**Describe the bug**
I had roughly $1400 USD staked in stable usdc on the previous token

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lissanro** [comment]
Please note that your message does not mention what issue you have or what your wallet address is, or if you filled the form in time. You mostly just submitted unedited template.

If your issue that you did not received the airdrop, either you did not have anything invested by the April 28, or you did not submit the form in time, or it wasn't submitted successfully, or you submitted the form with a wrong wallet address.

If you think your issue is different, and you decide to report your issue again, please make sure to include allrelevant information and clearly described what it is. Thank you.
