### ISSUE TITLE
staking under construction 

### ISSUE THREAD

**Issue by Beano54** [FalconX-DEX/Falx-Support#57]
**Describe the bug**
Ever since the new update, everything works except for the staking page… It has been displaying under construction ever since
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lissanro** [comment]
This sounds like a caching issue. Please clear cache of your browser. You did not fill the template properly so I cannot provide more specific instructions, please search the web about your specific browser in case you are not sure how to completely clear the cache. Since this is an issue on user's side, I am closing this issue, but feel free to ask additional questions if have an issue - in this case, make sure to provide all the details you did not fill in the issue template.
