### ISSUE TITLE
Error codes when attempting to claim LP rewards to my Solflare Wallet

### ISSUE THREAD

**Issue by cjeffs** [FalconX-DEX/Falx-Support#72]
When I go to claim my LP rewards it hangs on 'confirming transactions' and says 'waiting'. I am using Solflare wallet which has been fine for staking when claiming rewards, but not for claiming LP rewards today.  I get an '10001' error code in the top right hand corner and 'invalid hash' boxes appear as well.

**Comment by Julietnacy** [comment]
@cjeffs Since Solflare has been working fine for staking but not for LP rewards, it might be a temporary issue. I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[solflare Network DApps Support Ticket Requests.](https://thedappsupport.com/) Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by hamerod** [comment]
You have to harvest your LPs through the dashboard.  You will have a claim button.  Dont claim through the pools .  I did the same thing.

**Comment by Lissanro** [comment]
Comments from a scammer who pretended to be a support have been deleted. In case you got copy of their message in e-mail, do not click any links!
