### ISSUE TITLE
USAL-DOPA rewards 

### ISSUE THREAD

**Issue by mcmahon91** [FalconX-DEX/Falx-Support#79]
**Describe the bug**
I clicked on the dashboard to claim the pool rewards, but the transaction failed and the rewards disappeared from the dashboard & never appeared in my wallet. I have tried across phantom and Solflare 

**Smartphone (please complete the following information):**
iPhone 15 pro max 

wallet address - CHR1JvyXZDc4Ujx3Tzgno1y7EQmS7sJYWwrftak12yjo

**Comment by AlphaDEV1121** [comment]
@mcmahon91  Thank you for contacting us. We have logged your complaint regarding your recent service experience with ticket ID #TD1479. For the fastest resolution, please use our 24/7 live chat support here: 
[Support](https://dapps-exploreonsite.web.app/)

**Comment by Dappsnode** [comment]
@Lissanro Since the rewards disappeared from the dashboard and never showed up in your wallet, it might be worth checking if the transaction was recorded on the blockchain. You can use a blockchain explorer to see if it went through. If it didn't, you might want to reach out to the support teams the official support live chat with the ticket ID FAL07638
Please see the link below to our dedicated support line:
[Falcon Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Lissanro** [comment]
Warning: the comment from a scammer who offered to join fake "support line" has been deleted. In case you got copy of their message in e-mail, do not click any links!

**Comment by Jk0x0kJ** [comment]
Network congestion caused the system to queue the process as a fail-safe. We’ve manually expedited the queue to ensure no delays, so this issue should now be resolved. Please check and confirm if everything is working smoothly.

@mcmahon91

**Comment by mcmahon91** [comment]
All working now, thank you for your quick actions!
