### ISSUE TITLE
LP rewards claimed but NOT deposit

### ISSUE THREAD

**Issue by CHUDLPGC** [FalconX-DEX/Falx-Support#81]
**Describe the bug**
I have claimed today and yesterday for first time the LP rewards on the pools site. Transfered successfull but not being deposit on the wallet 
7Q9xV3KewrP6cDNrNisDup6g4K4C8hsQgKNL92WbP8uS
Thanks for your time 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser,

**Comment by Teresaevans** [comment]
Hey there @CHUDLPGC !

I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a message history or communication log. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you under the ID **FLX7638**, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link: [FalconX Dapps Support Ticket Requests](https://thedappsupport.com/). 

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by Lissanro** [comment]
Warning: the comment from a scammer who offered to join a fake "support ticket" has been deleted. In case you got copy of their message in e-mail, do not click any links!

**Comment by CHUDLPGC** [comment]
Any news on the issue ? Thx

**Comment by Lissanro** [comment]
This issue should be fixed, but if you experience the issues again, please let us know.

**Comment by CHUDLPGC** [comment]
I claimed again and not deposit the rewards into my account

Sebastián J Pérez Alvarez
620 984 243
***@***.***

Enviado desde Proton Mail para Android

-------- Mensaje original --------
El 13/11/24 21:00, Lissanro Rayen  ha escrito:

**Comment by Lissanro** [comment]
There should not be an issue with this anymore, if you try again, please make sure check recent transactions on solscan.io to confirm if you received the reward. But in case still does not work for, please let us know and I will reopen the issue to investigate further.
